### ISSUE TITLE
Failed to kick. Please check your values.

### ISSUE THREAD

**Issue by ghost** [dupondje/nrgkick-proto#3]
Hello,

Unfortunately it doesn't work for me with the web-if (index.html) I just get the error (Failed to kick. Please check your values).
Can someone tell me what I may be doing wrong. All fields are filled out accordingly.

Thank you

**Comment by dupondje** [comment]
There can be 100 reasons why it doesn't work.
Can you ping the IP of the NRGKick?
Open Dev console in the browser, and try again, it might give a clue (in the networking tab).
You did not change access code in the app perhaps?
Sure the serial number is correct?

**Comment by TSK7M** [comment]
I've changed the access code.
The Serial 7 digits before the S

<img width="488" alt="image" src="https://github.com/dupondje/nrgkick-proto/assets/151848159/e83a65d8-eaaf-41e9-8842-717a0b967326">
<img width="425" alt="image" src="https://github.com/dupondje/nrgkick-proto/assets/151848159/c979ec8e-ac51-49d0-bd13-2b6daadfcb54">

**"NotAuthorized"**
<img width="401" alt="image" src="https://github.com/dupondje/nrgkick-proto/assets/151848159/e6d70531-d5dd-4d60-afae-756bd0237e32">

**Comment by ghost** [comment]
It's settled, I need the new code, not the S/N. Thanks.

**Comment by dupondje** [comment]
Yes indeed.
The Serial Number derived 7 digits is the default access code.
If it was changed in the past, you need to use that new code to create some new UUID access :)
